name: Deploy Frontend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/react-frontend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/react-frontend:latest

      - name: Generate deployment package
        run: zip -r deploy.zip Dockerrun.aws.json

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: frontend
          environment_name: Frontend-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-808101329354
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
          use_existing_version_if_available: true